// SCSS
import gettingStartedContentStyles from "@/scss/pages/GettingStarted.module.scss";
// Next
import Image from "next/image";
// Translations
import { useTranslations } from "next-intl";
// Helpers
import translateWithRichText from "@/helpers/translateWithRichText";

const GettingStartedContentEntities = () => {
  const translateEntities = useTranslations("gettingStarted.content.entities");

  return (
    <section
      className={gettingStartedContentStyles.gettingStartedContentSection}
    >
      <h4>{translateEntities("title")}</h4>
      <div
        className={gettingStartedContentStyles.gettingStartedContentArticles}
      >
        <article
          className={gettingStartedContentStyles.gettingStartedContentArticle}
        >
          <h5>{translateEntities("articles.1.title")}</h5>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.1.descriptions.1"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.1.descriptions.2"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.1.descriptions.3"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.1.images.1")}
            alt={translateEntities("articles.1.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.1.descriptions.4"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.1.images.2")}
            alt={translateEntities("articles.1.imageAlt")}
          />
        </article>
        <article
          className={gettingStartedContentStyles.gettingStartedContentArticle}
        >
          <h5>{translateEntities("articles.2.title")}</h5>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.2.descriptions.1"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.2.descriptions.2"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.2.images.1")}
            alt={translateEntities("articles.2.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.2.descriptions.3"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.2.images.2")}
            alt={translateEntities("articles.2.imageAlt")}
          />
        </article>
        <article
          className={gettingStartedContentStyles.gettingStartedContentArticle}
        >
          <h5>{translateEntities("articles.3.title")}</h5>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.3.descriptions.1"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.3.descriptions.2"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.3.images.1")}
            alt={translateEntities("articles.3.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.3.descriptions.3"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.3.images.2")}
            alt={translateEntities("articles.3.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.3.descriptions.4"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.3.images.3")}
            alt={translateEntities("articles.3.imageAlt")}
          />
        </article>
        <article
          className={gettingStartedContentStyles.gettingStartedContentArticle}
        >
          <h5>{translateEntities("articles.4.title")}</h5>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.4.descriptions.1"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.4.descriptions.2"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.4.images.1")}
            alt={translateEntities("articles.4.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.4.descriptions.3"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.4.images.2")}
            alt={translateEntities("articles.4.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.4.descriptions.4"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.4.images.3")}
            alt={translateEntities("articles.4.imageAlt")}
          />
        </article>
        <article
          className={gettingStartedContentStyles.gettingStartedContentArticle}
        >
          <h5>{translateEntities("articles.5.title")}</h5>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.5.descriptions.1"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.5.descriptions.2"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.5.descriptions.3"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.5.images.1")}
            alt={translateEntities("articles.5.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.5.descriptions.4"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.5.images.2")}
            alt={translateEntities("articles.5.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.5.descriptions.5"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.5.images.3")}
            alt={translateEntities("articles.5.imageAlt")}
          />
        </article>
        <article
          className={gettingStartedContentStyles.gettingStartedContentArticle}
        >
          <h5>{translateEntities("articles.6.title")}</h5>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.6.descriptions.1"
            )}
          </p>
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.6.descriptions.2"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.6.images.1")}
            alt={translateEntities("articles.6.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.6.descriptions.3"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.6.images.2")}
            alt={translateEntities("articles.6.imageAlt")}
          />
          <p>
            {translateWithRichText(
              translateEntities,
              "articles.6.descriptions.4"
            )}
          </p>
          <Image
            width={720}
            height={480}
            src={translateEntities("articles.6.images.3")}
            alt={translateEntities("articles.6.imageAlt")}
          />
        </article>
      </div>
    </section>
  );
};

export default GettingStartedContentEntities;
